Change script permissions to make start-app.sh executable
This fixes the cause of the GitHub Actions frontend-tests job failing with the following error.
```
> tailspin-toys@0.0.1 test:e2e
> npx playwright test

[WebServer] /bin/sh: 1: ../scripts/start-app.sh: Permission denied
Error: Process from config.webServer was not able to start. Exit code: 126

Error: Process completed with exit code 1.
```
example: https://github.com/se-copilot-workshops/agents-in-sdlc/actions/runs/17666573677/job/50209219955?pr=15